CYELLOW = '\33[33m'
CRED = '\033[91m'
CEND = '\033[0m'

ERR_REGPROVIDER_LOAD_FAILED = -10

ERR_REGPARSER_INPUT_NOT_FOUND = 4
ERR_REGPARSER_ACTIONS_LOAD_FAILED = -20
ERR_REGPARSER_ACTIONS_UNSUPPORTED_ACTION = -21
ERR_REGPARSER_HIVE_NOT_INITIALIZED = -22

ERR_REGISTRY_UNKNOWN_ROOT = -31
ERR_REGISTRY_VALUE_TYPE_ERROR = -32

ERR_PROVIDER_INCORRECT_FUNCTION_SYNTAX = -40
ERR_PROVIDER_UNEXPECTED_INPUT_TYPE = -41
ERR_PROVIDER_DATABASE_COLUMNS_MISMATCH = -51
